server:
  port: 80
spring:
  application:
    name: server-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
    gateway:
      discovery:
        locator:
          enabled: true
        routes:
          - id: service-product
            uri: lb://service-product
            predicates:
              - Path=/*/product/** # 路径匹配  要求：商品模块微服务开发 请求URL路径 必须包含/admin/product/**